### ISSUE TITLE
How to compute the position and rotation error?

### ISSUE THREAD

**Issue by DanielCoelho112** [DanielCoelho112/localization_end_to_end#28]
I don't know how the papers are computing the position and rotation errors. 

**position**

Here I just computed the RMSE(pred,targ). The result is in meters, is this ok?

**rotation**

Here I blindly followed this [link](https://math.stackexchange.com/questions/3572459/how-to-compute-the-orientation-error-between-two-3d-coordinate-frames). I didn't understand anything, but they say the result is in rads. 

@miguelriemoliveira  I read what you wrote in ATOM, but I didn't understand as well.

**Comment by miguelriemoliveira** [comment]
Great
