### ISSUE TITLE
Create datasets using SfM in simulation

### ISSUE THREAD

**Issue by DanielCoelho112** [DanielCoelho112/localization_end_to_end#52]
To prove the usefulness of Synfeal we can collect the ground truth poses using SfM in simulation. This technique is commonly used among researchers, and therefore if we prove that the models can learn better using our datasets, we can state our point: current data collection techniques aren't accurate enough.

**Comment by DanielCoelho112** [comment]
Hi @miguelriemoliveira and @pmdjdias,

I wasn't able to run the SfM with 8500 images, it gave another error after 72h of heavy computation in deeplar.
Now I'm following your advice, I'm running SfM in batches of 500 images, and then combining the batches. So far so good. I have only one batch left to run, so I think I'll have this next dataset by next week.

Btw, @miguelriemoliveira you were right about the scaling factors. I looked through the code I found one error, now I am only using one scale factor.

Check the first 20 poses:
green - ours
orange - sfm 

![image](https://user-images.githubusercontent.com/73063947/168341930-129ed5ab-3611-4fc4-9705-8c2e95350e82.png)

The scale looks good now, but it looks like they are using another convention for the axis, it wont be a problem for deep learning, so I think it is ok to leave like this, right?

**Comment by miguelriemoliveira** [comment]
> The scale looks good now, but it looks like they are using another convention for the axis, it wont be a problem for deep learning, so I think it is ok to leave like this, right?

I don't think so. I think its best to track down this problem right away before it becomes harder.

I would say you need to get the orange arrows close to the green ones ...

**Comment by DanielCoelho112** [comment]
Hi @miguelriemoliveira,

> I would say you need to get the orange arrows close to the green ones ...

I followed your advice and now we have another problem :):

![image](https://user-images.githubusercontent.com/73063947/168423502-0fdbce8e-b4a0-4543-ba2e-8c91b36a92ce.png)

The camera poses from SfM are too close to ours... We are talking about millimeters of difference.
In my opinion, this is very strange, I did some research about the usual errors of SfM and found this table:

![image](https://user-images.githubusercontent.com/73063947/168423568-90826010-13ba-4011-bc84-abbda421e9e4.png)

Our SfM method is OpenMVG so we should be getting errors around 20/70 cm.

I'll look into this next week, I hope it is some bug in our pipeline.

**Comment by miguelriemoliveira** [comment]
I hope it is a bug. Could it be that now you are iterating every 500 images and that is a small set, what if it is larger? 

For debugging stuff I think you can  use just 500 or 1500 images (a smaller dataset). Even with that the sfm should be worse ...

**Comment by DanielCoelho112** [comment]
I looked through the code and didn't find any bugs...

Sfm is achieveng excelent results, check frame 6938:

our pose:

    -0.93869,0.09212,-0.33224,2.67705
    0.23972,-0.51819,-0.82098,2.61391
    -0.24779,-0.85029,0.46433,-0.15094
    0.00000,0.00000,0.00000,1.00000

sfm pose:
  
     -0.93866,0.09195,-0.33235,2.67393
     0.23987,-0.51863,-0.82073,2.61695
     -0.24777,-0.85004,0.46477,-0.15075
     0.00000,0.00000,0.00000,1.00000

![image](https://user-images.githubusercontent.com/73063947/168577913-0c8487d3-9cbf-40e5-a13a-24593cc4ef49.png)

I believe that if we decrease the number of images per batch, the SfM results would be worse, but I don't think that is a limitation of the method but a bad usage of the method.

I'm starting to believe that our core idea has some flaws and that maybe current data collection techniques aren't as inaccurate as we thought. 
In my opinion that doesn't mean that our idea of synthesizing data from reality is not worth pursuing. Although we are not achieving a signifactive increase in the ground-truth accuracy, we can create diverse and robust datasets (changing illumination, adding objects to the scene, creating new sensors...)

However, I believe that the data-centric paper might be at risk...

**Comment by miguelriemoliveira** [comment]
Ok, but thats somethong ... try to tune a bit more

**Comment by miguelriemoliveira** [comment]
It is good to write down exactly what you did, because we will need to be write this part extra carefully in the paper.

**Comment by miguelriemoliveira** [comment]
> Yes, this outcome is in line with the result of [this](https://openaccess.thecvf.com/content_ICCV_2017/papers/Walch_Image-Based_Localization_Using_ICCV_2017_paper.pdf) paper. They implemented SfM in a new dataset, and argued that SfM fail due to the textureless walls, which is exactly what is happening with us. We are just using Synfeal to help SfM giving acceptable results.

I think you know this already, but the style in which to do this would be something like:

An SfM was assistem manually because it failed due to this and that situation. In fact, this is consistent with the results reported in [X], were authrors describe ...

You have a lot of these arguments, And using them in the paper makes it so much stronger ... I think you are on the way for writing an amazing paper. keep it up.
