### ISSUE TITLE
Collecting datasets using Visual Odometry

### ISSUE THREAD

**Issue by DanielCoelho112** [DanielCoelho112/localization_end_to_end#55]
As discussed over lunch, we could implement a visual odometry technique to produce another approach. @miguelriemoliveira please put here the link to the repo you mentioned.

**Comment by miguelriemoliveira** [comment]
Hi @DanielCoelho112 ,

https://github.com/miguelriemoliveira/RustBot

This one has a lot of extra stuff not related to slam. You have to distill it.

We have used something called viso2, which is a simple visual odometry library.

https://github.com/miguelriemoliveira/RustBot/blob/master/rustbot_bringup/launch/viso2_withtf.launch

We also did some tests with rtab which does the same, but I alwaysthought it was very complec. Francisco Power worked on this in his thesis, we can talk to him ...
