### ISSUE TITLE
Implement PoseNet with ResNet as feature extractor

### ISSUE THREAD

**Issue by DanielCoelho112** [DanielCoelho112/localization_end_to_end#63]

**Comment by miguelriemoliveira** [comment]
Feature extractor?

**Comment by DanielCoelho112** [comment]
Yes. original PoseNet uses GoogleNet as feature extractor followed by fully connected layers:
![image](https://user-images.githubusercontent.com/73063947/173853301-7a49b882-fdcb-46b3-929c-357ac0fd226d.png)

Some authors have replaced GoogleNet with ResNet. It is just a minor modification and we could easily gain another model.

**Comment by miguelriemoliveira** [comment]
Ok, makes sense.

**Comment by DanielCoelho112** [comment]
Done. Results are updated in #61.

**Comment by miguelriemoliveira** [comment]
The table is looking great! Keep it up.
