### ISSUE TITLE
Download 3D model of a indoor scene

### ISSUE THREAD

**Issue by DanielCoelho112** [DanielCoelho112/localization_end_to_end#69]
To prove that Synfeal works in other datasets, we should download a 3D model.

**Comment by DanielCoelho112** [comment]
Hi @miguelriemoliveira and @pmdjdias,

I found these 3D models:
![chapel](https://user-images.githubusercontent.com/73063947/174648891-38888b7e-bbe5-46ca-a263-85c75717953f.png)
![grange](https://user-images.githubusercontent.com/73063947/174648897-9fbfb2df-6194-403e-b5f0-28c5d8d50a1a.png)

I think the first one is quite good for us, what do you say?

**Comment by pmdjdias** [comment]
It would be better if we could use uor models... I have some from my time in Italy... The geometry of the firste does not seem very good (seems like the ceiling is kind of "wavy"...
<img width="374" alt="image" src="https://user-images.githubusercontent.com/17404192/174655962-e82a02b8-d86d-4fbf-897f-a40ea51a999c.png">

**Comment by DanielCoelho112** [comment]
We will advance with the first model due to its geometry.
