### ISSUE TITLE
Create a dataset using Santuario as the 3D model

### ISSUE THREAD

**Issue by DanielCoelho112** [DanielCoelho112/localization_end_to_end#77]

**Comment by miguelriemoliveira** [comment]
Very nice. Agree, extra 4000 for test. But those should cover the entire
space...


I think I can improve rhe visualization a bit. Can you let me know how you
visualize so i can try a few tricks?

**Comment by DanielCoelho112** [comment]
Hi @miguelriemoliveira,

first download seq22 from[ here](https://uapt33090-my.sharepoint.com/:f:/g/personal/danielsilveiracoelho_ua_pt/Eq-KV5MbmtpOo9PdgcWkZVkBlmkLszmjil0ZWXptYspIyA?e=4va6LF) 

then run:

    roslaunch localbot_localization visualize_dataset.launch dataset:=seq22

seq22 is from the lab 024, so you may have to change the directory in the visualize_dataset script
