### ISSUE TITLE
Definition of the journal

### ISSUE THREAD

**Issue by DanielCoelho112** [DanielCoelho112/localization_end_to_end#81]

**Comment by DanielCoelho112** [comment]
Hi @miguelriemoliveira,

I looked through the papers, and the only paper that wasn't published at a conference was published in IEEE Transactions on Automation Science and Engineering. IF=6.636.

https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=8856

I think it could be a good option, what do you say?

**Comment by miguelriemoliveira** [comment]
Not sure. Honestly, I think the quality of your work deserves pointing higher. Lets talk about it.

**Comment by DanielCoelho112** [comment]
IEEE Transactions on Pattern Analysis and Machine Intelligence looks very nice, and I found some papers about navigation and localization from there. What do you say?

**Comment by miguelriemoliveira** [comment]
This is the Holy Grail of journals. I only know two or three people in Portugal who published here: 

Normally this requires a CVPR first, then an expansion to the journal.

In any case I would send it there and then we'll see.

NOTE: If we are going here this is the best of the best, so I would do everything do make the best paper possible, even if we have to go back to lights and occlusions.

Check the number of pages for PAMI please.

**Comment by miguelriemoliveira** [comment]
Also, I would make the repo private for now. You can say to github that you work at the university and they will give you access to private repos.

**Comment by DanielCoelho112** [comment]
> Check the number of pages for PAMI please.

14 double-column pages. I think it may not be enough... And also, I'm a bit skeptical about going back to lights and occlusions. That would require a lot of work, and I think we already have a lot to show.

TIP has a maximum number of pages of 30 double-column pages, which is better. 

I think we should submit until the end of July, and if we go back to lights and occlusions I think it is not possible.
What do you think TIP with the work we have so far?
