### ISSUE TITLE
Synfeal - Architecture

### ISSUE THREAD

**Issue by DanielCoelho112** [DanielCoelho112/localization_end_to_end#82]
Hi @miguelriemoliveira and @pmdjdias,

Suggestions?

![synfeal_arch_img](https://user-images.githubusercontent.com/73063947/177515820-79cf50a1-7d18-4851-aa7c-ec98350daa08.png)

**Comment by DanielCoelho112** [comment]
Olá @pmdjdias,

Já fiz as alterações. No automatic data collection aquela imagem não é a final, ainda vai sofrer algumas alterações. No synthetic dataset penso que é melhor manter da forma simples, até porque assim vê-se que seguimos o formato dos datasets mais tradicionais.

![synfeal_architecture (9)](https://user-images.githubusercontent.com/73063947/177748243-72cdb4ec-f640-4dd4-a523-f4a4badb44f8.png)

**Comment by miguelriemoliveira** [comment]
Olá bom dia,

eu acho que a foto da câmara ficava bem. Podia não ser uma rgbd, mas uma qq camara ficava bem porque é um diagrama pictográfico.

A parte dentro do synfeal acho que podemos melhorar ... Vou ligar Daniel.

**Comment by miguelriemoliveira** [comment]
Yes, much better. I have some tips though. Perhaps we can meet online?

**Comment by DanielCoelho112** [comment]
Yes. I am available all day. Call me when you are available.

**Comment by miguelriemoliveira** [comment]
I am with the SVPI exame all day, but perhaps I can call at 12h or 14h.

**Comment by DanielCoelho112** [comment]
At 12h I might be having lunch, but at 14h it would work.

**Comment by DanielCoelho112** [comment]
New version:

![synfeal](https://user-images.githubusercontent.com/73063947/179122633-261b04ef-85c9-4ae4-989e-8553446c7a14.png)

**Comment by miguelriemoliveira** [comment]
Hi @DanielCoelho112 ,

I think it is much better. Congratullations.
